### ISSUE TITLE
Image in the navigation bar not shown

### ISSUE THREAD

**Issue by rherrmann** [bchetty/jekyllBasic#1]
Setting the `avatar` property in `_config.yml` has no effect.

**Comment by bchetty** [comment]
@rherrmann The property is just there in the **_config.yml** file. It's not used in any of the "layouts" or the "includes" files. If you want to use that property (**site.avatar**), just customize your forked repo and add code in one of the "includes" files or maybe in the "aboutme" page. If you need help, just reply back.
